[config]
schemaVersion = "0.0.1"

[package]
namespace = "ninesolsmodding"
name = "UnityExplorer"
# versionNumber = "4.9.0"
versionNumber = "0.1.0"
description = "An in-game UI for exploring, debugging and modifying Unity games. "
websiteUrl = "https://github.com/sinai-dev/UnityExplorer"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../out"

[[build.copy]]
source = "./build/mod/plugins/sinai-dev-UnityExplorer"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["nine-sols"]

[publish.categories]
nine-sols = ["tools"]
